# Generated by Django 4.1.7 on 2025-02-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('command', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('device_location', models.CharField(blank=True, max_length=255, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('min_response_time', models.FloatField(blank=True, null=True)),
                ('max_response_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.BigIntegerField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=50)),
                ('device_province', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
