# Generated by Django 4.1.7 on 2025-01-15 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BotAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botanalytics',
            options={'verbose_name_plural': 'Bot Analytics'},
        ),
        migrations.RemoveField(
            model_name='botanalytics',
            name='success',
        ),
        migrations.AddField(
            model_name='botanalytics',
            name='device_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botanalytics',
            name='command',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botanalytics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
