# Generated by Django 4.1.7 on 2025-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotAnalytics', '0002_alter_botanalytics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botanalytics',
            options={},
        ),
        migrations.AddField(
            model_name='botanalytics',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='botanalytics',
            name='command',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='botanalytics',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
