# Generated by Django 4.1.7 on 2025-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotAnalytics', '0003_alter_botanalytics_options_botanalytics_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanalytics',
            name='max_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botanalytics',
            name='min_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botanalytics',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
