# Generated by Django 4.2.4 on 2024-11-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_device_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name_hy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='parent_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='parent_name_hy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
