name: Deploy to AWS EC2

on:
  push:
    branches:
      - staging 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY}}

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_HOST}}
        EC2_HOST: ${{ secrets.EC2_IP}}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          cd home/ubuntu/ClimateNetBot/climate_bot/
          
          # Pull the latest changes
          git pull origin staging
          
          # Install dependencies if required
          pip install -r requirements.txt
          
          # Restart the bot service
          sudo systemctl restart telegram_bot.service
        EOF
