name: Deploy on push main # Description: This workflow triggers deployment when code is pushed to the main branch

on:
  push:
    branches:
      - main  # Trigger: Deploy when pushing changes to the main branch
jobs:
  Deploy:
    runs-on: ubuntu-latest  # Specify the operating system for the job
    steps:
      - name: Deploy in EC2 and execute commands  # Step: Deploy code and execute commands on the EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Environment variable: SSH private key
          HOSTNAME: ${{ secrets.PROD_IP }}  # Environment variable: Hostname of the EC2 instance
          USERNAME: ${{ secrets.EC2_USERNAME }}  # Environment variable: SSH username
        run: |
          set -euo pipefail  
          trap 'exit 0' EXIT 
          
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          ssh -o StrictHostKeyChecking=accept-new -i private_key ${USERNAME}@${HOSTNAME} '
          
          sudo apt update && \
          cd /home/ubuntu/ClimateNetBot/climate_bot && \
          
          git stash && \
          git checkout main && \
          git pull origin main && \
          
          # Install the dependencies
          source venv/bin/activate && \
          pip install -r requirements.txt && \
          
          # Restart the bot service
          sudo systemctl restart telegram_bot.service '
